import { calculateSimilarity } from "./similarity.js";
import { calculatePenalties } from "./penalties.js";
import { calculateDurationScore } from "./duration.js";
import { extractVersionTokens } from "./normalization.js";

// "- Topic" channels are auto-generated by YouTube/YT Music directly
// from a label's catalog metadata, so a channel-name match there is a
// much stronger artist signal than fuzzy-matching against a video title.
function isTopicChannel(channelTitle = "") {
  return /- topic$/i.test(channelTitle.trim());
}

export function scoreMatch(normalizedTrack, youtubeResult) {
  const spotifyTitle = normalizedTrack.title || "";
  const spotifyArtists = (normalizedTrack.artists || []).join(" ");

  const youtubeTitle = youtubeResult.title || "";
  const youtubeChannel = youtubeResult.channelTitle || "";

  // ==============================
  // TITLE SIMILARITY
  // ==============================
  const titleScore = calculateSimilarity(spotifyTitle, youtubeTitle);

  // ==============================
  // ARTIST SIMILARITY
  // ==============================
  // Compare against the channel name directly first — for "- Topic"
  // channels and official artist channels this is far more reliable
  // than fuzzy-matching against a noisy video title. Fall back to
  // (title + channel) so featured artists mentioned only in the title
  // still contribute.
  const channelScore = calculateSimilarity(spotifyArtists, youtubeChannel);
  const combinedTextScore = calculateSimilarity(
    spotifyArtists,
    `${youtubeTitle} ${youtubeChannel}`
  );
  const artistScore = Math.max(channelScore, combinedTextScore);

  // ==============================
  // DURATION
  // ==============================
  const durationScore = calculateDurationScore(
    normalizedTrack.durationMs,
    youtubeResult.durationSeconds
  );

  // ==============================
  // PENALTIES / BONUSES
  // ==============================
  const spotifyVersionTokens = extractVersionTokens(spotifyTitle);
  const { penalty, bonus, matchedKeywords } = calculatePenalties(
    youtubeTitle,
    spotifyVersionTokens
  );

  const topicBonus = isTopicChannel(youtubeChannel) ? 5 : 0;

  // ==============================
  // FINAL SCORE
  // ==============================
  // When duration data isn't available, redistribute its weight across
  // title/artist rather than silently treating the missing signal as 0.
  let rawScore;
  if (durationScore === null) {
    rawScore = titleScore * 0.6 + artistScore * 0.4;
  } else {
    rawScore = titleScore * 0.45 + artistScore * 0.3 + durationScore * 0.25;
  }

  const finalScore = Math.max(
    0,
    Math.min(100, rawScore - penalty + bonus + topicBonus)
  );

  return {
    score: Math.round(finalScore),
    breakdown: {
      titleScore: Math.round(titleScore),
      artistScore: Math.round(artistScore),
      durationScore: durationScore === null ? null : Math.round(durationScore),
      penalty,
      bonus: bonus + topicBonus,
      matchedKeywords,
    },
  };
}